name: canyou_widget
description: CanYou common components package.
version: 0.0.1+1
homepage: https://github.com/CanYouSZ/canyou_widget
repository: https://github.com/CanYouSZ/canyou_widget

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
