name: canyou_widget
description: CanYou software common components package.Contains commonly used widgets, utility classes, and common libraries to unify the project widget style and avoid repetitive work.
version: 0.0.1+2-nullsafety.0
homepage: https://github.com/CanYouSZ/canyou_widget
repository: https://github.com/CanYouSZ/canyou_widget

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
